name: Goha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  cloud_firestore: ^2.5.4
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.1
  firebase_core: ^1.7.0
  firebase_database: ^8.0.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.1
  flutter_phone_direct_caller: ^2.1.0
  font_awesome_flutter: ^9.2.0
  path: ^1.8.0
  path_provider: ^2.0.6
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "dev_assets/Brandat.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/Brandat.png"

  assets:
    - assets/images/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets\fonts\JetBrainsMono-VariableFont_wght.ttf

    - family: Lalezar
      fonts:
        - asset: assets\fonts\Lalezar-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
